In [2]:
# A Euclidian Vector is a geometric object that has magnitude/length and direction. 

import numpy as np

# These can be displayed as rows or columns with basic Numpy:

vector_r = np.array([15.45,  # Open
                     15.98,  # High
                     15.35,  # Low
                     15.60]) # Close

vector_c = np.array([[15.45],  # Open
                     [15.98],  # High
                     [15.35],  # Low
                     [15.60]]) # Close

# Similarly, you could represent these as lists of floats

In [12]:
# Addition:

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

a + b == np.array([5, 7, 9])

array([ True,  True,  True])

In [15]:
# Subtraction: 

a = np.array([5, 7, 9])
b = np.array([4, 5, 6])

a - b == np.array([1, 2, 3])

array([ True,  True,  True])

In [21]:
# Vector Sum

a = np.array([1, 2])
b = np.array([3, 4])
c = np.array([5, 6])
d = np.array([7, 8])

sum([a, b, c, d]) == np.array([16, 20])

array([ True,  True])

In [22]:
# Scalar Multiply

a = np.array([1, 2, 3])
b = 2

a * b == np.array([2, 4, 6])

array([ True,  True,  True])

In [33]:
# Vector Mean

a = np.array([1, 2])
b = np.array([3, 4])
c = np.array([5, 6])

np.mean([a, b, c], axis=0)

array([3., 4.])

In [35]:
# Dot Product

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.dot(a, b) # (1 * 4) + (2 * 5) + (3 * 6) = 32

32

In [36]:
# sum of squares

np.dot(a, a)

14

In [39]:
# Squared Distance

def sq_dist(a, b):
    v = a - b
    return np.dot(v, v)

sq_dist(a, b)

27

In [41]:
# Magnitude/Length

import math

def mag(a):
    return math.sqrt(np.dot(a, a))

mag(a)

3.7416573867739413

In [44]:
# Distance

def dist(a, b):
    return mag(a - b)
    
dist(a, b)

5.196152422706632

In [64]:
# Matrices

a = np.array([1, 2])
b = np.array([3, 4])

c = np.array([a, b]) # Do not use np.matrix

c

array([[1, 2],
       [3, 4]])

In [65]:
# Shape

c.shape

(2, 2)

In [66]:
# row

c[0]

array([1, 2])

In [77]:
# Column
c[:, 0]

array([1, 3])

In [82]:
# Construct based on shape

np.zeros(shape=(5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [83]:
# Identity Matrix

np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [86]:
# user 0  1  2  3  4  5  6  7  8  9

friends = np.array([
    [0, 1, 1, 0, 0, 0, 0, 0, 0, 0], # user 0
    [1, 0, 1, 1, 0, 0, 0, 0, 0, 0], # user 1
    [1, 1, 0, 1, 0, 0, 0, 0, 0, 0], # user 2
    [0, 1, 1, 0, 1, 0, 0, 0, 0, 0], # user 3
    [0, 0, 0, 1, 0, 1, 0, 0, 0, 0], # user 4
    [0, 0, 0, 0, 1, 0, 1, 1, 0, 0], # user 5
    [0, 0, 0, 0, 0, 1, 0, 0, 1, 0], # user 6
    [0, 0, 0, 0, 0, 1, 0, 0, 1, 0], # user 7
    [0, 0, 0, 0, 0, 0, 1, 1, 0, 1], # user 8
    [0, 0, 0, 0, 0, 0, 0, 0, 1, 0]] # user 9
)

In [87]:
friends[0][2] == 1

True

In [89]:
friends[0][8] == 0

True

In [90]:
friends_of_five = [i for i, is_friend in enumerate(friends[5]) if is_friend]

In [91]:
friends_of_five

[4, 6, 7]